project:
  type: website
  output-dir: docs
  

website:
  title: "SpatialDataChronicles"
  navbar:
    left: 
      - text: Resume
        href: Sambadi Majumder CV.pdf
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SamMajumder
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

